### ISSUE TITLE
results should contain links 

### ISSUE THREAD

**Issue by stuartayeates** [MarkEEaton/open-journal-matcher#6]
The result list should contain links. 

Ideally they'd link to the journals themselves, but that would require the code to keep track of the extra information. Since you already have the ISSN, you could either link back to the DOAJ using a URL like: https://doaj.org/toc/1836-0394 or to the ISSN portal like: https://portal.issn.org/resource/ISSN/1836-0394 I had thought of using the crossref search like https://search.crossref.org/?q=1836-0394 but that fails for some journals that doesn't support DOIs and crossref.

Clearly the DOAJ link is likely to be the most useful to the most readers.

**Comment by MarkEEaton** [comment]
Thanks for this! This was actually in the code a few commits ago  -- it was taken out with c578cd58ffd893cb33250e6ee40c41fa6d0a6350 -- owing to a security issue using hrefs with untrusted content. The problem is described in this post: https://smirnov-am.github.io/securing-flask-web-applications/. 

I am very interested in suggestions as to how to reimplement this securely!

**Comment by MarkEEaton** [comment]
This page also describes the problem: https://flask.palletsprojects.com/en/1.1.x/security/

**Comment by MarkEEaton** [comment]
Ack, I just realized your comment has the solution to this problem!

Instead of using the untrusted URL for the journal homepage provided by the API, a trusted URL can be constructed from the DOAJ base URL plus the ISSN. Thank you, this is perfect. Will implement in the next release.

**Comment by stuartayeates** [comment]
Given that there are two obvious components to carry links, I'd encourage you to link to DOAJ for the journal name and  https://portal.issn.org/resource/ISSN/1836-0394 for the ISSN,  The ISSN portal isn't necessarily the most useful link, but it's certainly the most authoritative.

**Comment by MarkEEaton** [comment]
I just wanted to let you know that I am making progress on this. I implemented a proper `Content-Security-Policy`, which is needed to generate secure links in this case. Hopefully this can be wrapped up soon!
